import { AnimalSpecies, AnimalGender, AnimalStatus, type Animal } from '../types/animal';

export class AnimalRepository {
    private readonly networkDelayMs = 500;
    
    async getAnimals(): Promise<Animal[]> {
        await new Promise(resolve => setTimeout(resolve, this.networkDelayMs));
        return this.getMockAnimals();
    }
    
    private getMockAnimals(): Animal[] {
        return [
            {
                id: '1',
                name: 'Fluffy',
                photoUrl: 'placeholder_cat',
                location: { city: 'Pruszkow', radiusKm: 5 },
                species: AnimalSpecies.CAT,
                breed: 'Maine Coon',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '18/11/2025',
                description: 'Friendly orange tabby cat, last seen near the park.',
                email: 'john.doe@example.com',
                phone: '+48 123 456 789'
            },
            {
                id: '2',
                name: 'Rex',
                photoUrl: 'placeholder_dog',
                location: { city: 'Warsaw', radiusKm: 10 },
                species: AnimalSpecies.DOG,
                breed: 'German Shepherd',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '17/11/2025',
                description: 'Large black and tan dog, wearing red collar.',
                email: 'anna.smith@example.com',
            },
            {
                id: '3',
                name: 'Bella',
                photoUrl: 'placeholder_cat',
                location: { city: 'Krakow', radiusKm: 3 },
                species: AnimalSpecies.CAT,
                breed: 'Siamese',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.FOUND,
                lastSeenDate: '19/11/2025',
                description: 'Blue-eyed white cat found near train station.',
                phone: '+48 987 654 321'
            },
            {
                id: '4',
                name: 'Buddy',
                photoUrl: 'placeholder_dog',
                location: { city: 'Wroclaw', radiusKm: 7 },
                species: AnimalSpecies.DOG,
                breed: 'Labrador Retriever',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '16/11/2025',
                description: "Yellow lab, very friendly, responds to 'Buddy'.",
                email: 'mike@example.com',
                phone: '+48 111 222 333'
            },
            {
                id: '5',
                name: 'Tweety',
                photoUrl: 'placeholder_bird',
                location: { city: 'Gdansk', radiusKm: 15 },
                species: AnimalSpecies.BIRD,
                breed: 'Cockatiel',
                gender: AnimalGender.UNKNOWN,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '15/11/2025',
                description: 'Gray and yellow bird, escaped from balcony.',
                email: 'sarah@example.com',
            },
            {
                id: '6',
                name: 'Snowball',
                photoUrl: 'placeholder_cat',
                location: { city: 'Poznan', radiusKm: 8 },
                species: AnimalSpecies.CAT,
                breed: 'Persian',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '14/11/2025',
                description: 'White long-haired cat, very shy.',
            },
            {
                id: '7',
                name: 'Snoopy',
                photoUrl: 'placeholder_dog',
                location: { city: 'Lodz', radiusKm: 12 },
                species: AnimalSpecies.DOG,
                breed: 'Beagle',
                gender: AnimalGender.MALE,
                status: AnimalStatus.FOUND,
                lastSeenDate: '20/11/2025',
                description: 'Tri-color beagle found wandering near shopping center.',
                email: 'finder@example.com',
                phone: '+48 555 666 777'
            },
            {
                id: '8',
                name: 'Thumper',
                photoUrl: 'placeholder_rabbit',
                location: { city: 'Katowice', radiusKm: 6 },
                species: AnimalSpecies.RABBIT,
                breed: 'Dwarf Rabbit',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.CLOSED,
                lastSeenDate: '13/11/2025',
                description: 'Small gray rabbit, reunited with owner.',
                email: 'owner@example.com',
                phone: '+48 444 333 222'
            },
            {
                id: '9',
                name: 'Shadow',
                photoUrl: 'placeholder_dog',
                location: { city: 'Szczecin', radiusKm: 20 },
                species: AnimalSpecies.DOG,
                breed: 'Husky',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '12/11/2025',
                description: 'Blue-eyed Siberian Husky, very energetic.',
                phone: '+48 888 999 000'
            },
            {
                id: '10',
                name: 'Whiskers',
                photoUrl: 'placeholder_cat',
                location: { city: 'Bialystok', radiusKm: 4 },
                species: AnimalSpecies.CAT,
                breed: 'British Shorthair',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '11/11/2025',
                description: 'Gray tabby cat with green eyes.',
                email: 'cat.owner@example.com',
            },
            {
                id: '11',
                name: 'Luna',
                photoUrl: 'placeholder_dog',
                location: { city: 'Lublin', radiusKm: 9 },
                species: AnimalSpecies.DOG,
                breed: 'Golden Retriever',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '10/11/2025',
                description: 'Golden retriever puppy, very playful.',
                email: 'luna.owner@example.com',
                phone: '+48 222 333 444'
            },
            {
                id: '12',
                name: 'Charlie',
                photoUrl: 'placeholder_cat',
                location: { city: 'Rzeszow', radiusKm: 5 },
                species: AnimalSpecies.CAT,
                breed: 'Ragdoll',
                gender: AnimalGender.MALE,
                status: AnimalStatus.FOUND,
                lastSeenDate: '21/11/2025',
                description: 'Blue-eyed ragdoll cat, found in garage.',
                email: 'finder123@example.com',
            },
            {
                id: '13',
                name: 'Max',
                photoUrl: 'placeholder_dog',
                location: { city: 'Torun', radiusKm: 11 },
                species: AnimalSpecies.DOG,
                breed: 'Dachshund',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '09/11/2025',
                description: 'Small brown dachshund, wears blue collar.',
                email: 'max.family@example.com',
                phone: '+48 333 444 555'
            },
            {
                id: '14',
                name: 'Milo',
                photoUrl: 'placeholder_bird',
                location: { city: 'Gliwice', radiusKm: 6 },
                species: AnimalSpecies.BIRD,
                breed: 'Parrot',
                gender: AnimalGender.UNKNOWN,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '08/11/2025',
                description: "Green parrot, can say 'Hello'.",
                phone: '+48 666 777 888'
            },
            {
                id: '15',
                name: 'Daisy',
                photoUrl: 'placeholder_cat',
                location: { city: 'Bydgoszcz', radiusKm: 7 },
                species: AnimalSpecies.CAT,
                breed: 'Bengal',
                gender: AnimalGender.FEMALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '07/11/2025',
                description: 'Spotted bengal cat, very active.',
                email: 'daisy.home@example.com',
                phone: '+48 777 888 999'
            },
            {
                id: '16',
                name: 'Rocky',
                photoUrl: 'placeholder_dog',
                location: { city: 'Olsztyn', radiusKm: 13 },
                species: AnimalSpecies.DOG,
                breed: 'Rottweiler',
                gender: AnimalGender.MALE,
                status: AnimalStatus.ACTIVE,
                lastSeenDate: '06/11/2025',
                description: 'Large rottweiler, friendly despite size.',
                email: 'rocky.owner@example.com',
            }
        ];
    }
}

export const animalRepository = new AnimalRepository();

