openapi: 3.0.3
info:
  title: PetSpot Announcement Details API
  description: API endpoint for fetching detailed information about a specific pet announcement
  version: 1.0.0
  contact:
    name: PetSpot Backend Team

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /api/v1/announcements/{id}:
    get:
      summary: Get details of a specific pet announcement
      description: |
        Retrieves complete details of a pet announcement by its unique ID.
        Returns all fields including optional contact and reward information.
        Response is a single announcement object (no wrapper).
      operationId: getAnnouncementById
      tags:
        - Announcements
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the announcement (UUID v4)
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Successfully retrieved announcement details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncementDetails'
              examples:
                fullDetails:
                  summary: Complete announcement with all optional fields
                  value:
                    id: "550e8400-e29b-41d4-a716-446655440000"
                    petName: Max
                    species: dog
                    status: missing
                    photoUrl: http://localhost:3000/images/max.jpg
                    lastSeenDate: "2024-11-15"
                    latitude: 52.2297
                    longitude: 21.0122
                    breed: Golden Retriever
                    microchipNumber: "123456789012345"
                    contactEmail: owner@example.com
                    contactPhone: "+48123456789"
                    reward: 500.0
                    description: Friendly golden retriever, responds to Max. Last seen in Mokotów area.
                    createdAt: "2024-11-20T10:30:00.000Z"
                    updatedAt: "2024-11-20T10:30:00.000Z"
                minimalDetails:
                  summary: Announcement with minimal optional fields
                  value:
                    id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                    petName: Luna
                    species: cat
                    status: found
                    photoUrl: http://localhost:3000/images/luna.jpg
                    lastSeenDate: "2024-11-20"
                    latitude: 52.2300
                    longitude: 21.0130
                    breed: null
                    microchipNumber: null
                    contactEmail: null
                    contactPhone: "+48987654321"
                    reward: null
                    description: Gray tabby cat, very shy
                    createdAt: "2024-11-20T12:00:00.000Z"
                    updatedAt: "2024-11-20T12:00:00.000Z"
        '404':
          description: Announcement not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not Found
                message: Announcement with id 00000000-0000-0000-0000-000000000000 not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Internal server error
                message: Database query failed

components:
  schemas:
    AnnouncementDetails:
      type: object
      required:
        - id
        - petName
        - species
        - status
        - photoUrl
        - lastSeenDate
        - latitude
        - longitude
        - description
        - contactPhone
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique announcement identifier (UUID v4)
          example: "550e8400-e29b-41d4-a716-446655440000"
        petName:
          type: string
          description: Name of the pet
          minLength: 1
          example: Max
        species:
          type: string
          description: Species of the pet
          enum: [dog, cat, bird, other]
          example: dog
        status:
          type: string
          description: Current status of the announcement
          enum: [missing, found]
          example: missing
        photoUrl:
          type: string
          format: uri
          description: URL to pet photo (relative or absolute)
          example: http://localhost:3000/images/max.jpg
        lastSeenDate:
          type: string
          format: date
          description: Date when pet was last seen (ISO 8601 date format YYYY-MM-DD)
          example: "2024-11-15"
        latitude:
          type: number
          format: double
          description: Latitude of last seen location
          minimum: -90
          maximum: 90
          example: 52.2297
        longitude:
          type: number
          format: double
          description: Longitude of last seen location
          minimum: -180
          maximum: 180
          example: 21.0122
        breed:
          type: string
          nullable: true
          description: Breed of the pet (optional)
          example: Golden Retriever
        microchipNumber:
          type: string
          nullable: true
          description: Pet microchip identification number (optional, typically 15 digits)
          example: "123456789012345"
        contactEmail:
          type: string
          format: email
          nullable: true
          description: Contact email address for this announcement (optional)
          example: owner@example.com
        contactPhone:
          type: string
          description: Contact phone number for this announcement
          minLength: 1
          example: "+48123456789"
        reward:
          type: number
          format: double
          nullable: true
          description: Reward amount offered for finding the pet (optional, in local currency)
          minimum: 0
          example: 500.0
        description:
          type: string
          description: Detailed description of the pet and circumstances
          minLength: 1
          example: Friendly golden retriever, responds to Max. Last seen in Mokotów area.
        createdAt:
          type: string
          format: date-time
          description: Timestamp when announcement was created (ISO 8601 datetime with timezone)
          example: "2024-11-20T10:30:00.000Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when announcement was last updated (ISO 8601 datetime with timezone)
          example: "2024-11-20T10:30:00.000Z"
    
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error type or code
          example: Not Found
        message:
          type: string
          description: Human-readable error message
          example: Announcement with id 00000000-0000-0000-0000-000000000000 not found

