import type { Knex } from 'knex';

const ANNOUNCEMENTS = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    pet_name: 'Fredi Kamionka Gmina Burzenin',
    species: 'DOG',
    breed: 'York',
    gender: 'MALE',
    description: '"Zaginął piesek York wabi się Fredi Kamionka gmina burzenin" Spotterka',
    location: 'Kamionka',
    location_radius: 5,
    last_seen_date: '2025-11-18',
    email: 'spotterka@example.pl',
    phone: '+48 123 456 789',
    photo_url: 'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_1010.jpg',
    status: 'ACTIVE',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    pet_name: 'Luna',
    species: 'CAT',
    breed: null,
    gender: 'FEMALE',
    description: 'Zaginęła czarna kotka Luna z charakterystycznymi białymi łapkami i małą białą plamką na piersi. Ma około 3 lata, waży ok. 4 kg, bardzo nieśmiała i może się chować przed obcymi ludźmi. Luna ma zielone oczy i nosi różową obrożę z dzwoneczkiem. Widziana ostatnio w okolicy ul. Kazimierza Wielkiego w Krakowie. Luna jest bardzo przywiązana do domu i nigdy nie uciekała. Jest karmiona specjalną karmą ze względu na wrażliwy żołądek. Jeśli ją spotkasz, nie próbuj łapać - ucieknie. Zamiast tego zadzwoń pod podany numer telefonu. Luna reaguje na swoje imię, ale tylko gdy jest wypowiadane spokojnym, łagodnym tonem. Jest zaszczepiona, wykastrowana i ma czip. Bardzo tęsknimy za nią i prosimy o jakiekolwiek informacje. Oferujemy nagrodę. Luna to członek naszej rodziny i jej brak jest dla nas bardzo bolesny. Jeśli ktoś widział kotka o tym opisie, prosimy o pilny kontakt. Sprawdzaliśmy już wszystkie schroniska i kliniki weterynaryjne w okolicy, niestety bez rezultatu. Luna może być przestraszona i sama.',
    location: 'Kraków',
    location_radius: null,
    last_seen_date: '2025-11-15',
    email: null,
    phone: '555-0102',
    photo_url: 'https://koty.pl/wp-content/uploads/2025/08/tuxedo_cat_7b7e699fc0.jpg',
    status: 'ACTIVE',
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    pet_name: 'Piorun',
    species: 'BIRD',
    breed: 'Papużka falista',
    gender: 'UNKNOWN',
    description: 'Żółta papużka, bardzo gadatliwa. Zna zwroty "cześć" i "piękny ptaszek".',
    location: 'Wrocław',
    location_radius: 3,
    last_seen_date: '2025-11-17',
    email: 'anna.nowak@example.pl',
    phone: null,
    photo_url: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400',
    status: 'ACTIVE',
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    pet_name: 'Burek',
    species: 'DOG',
    breed: 'Mieszaniec labradora',
    gender: 'MALE',
    description: 'Brązowy kundelek, średniej wielkości. Nosi niebieską obrożę z identyfikatorem.',
    location: 'Gdańsk',
    location_radius: 10,
    last_seen_date: '2025-11-10',
    email: 'michal.wisniewski@example.pl',
    phone: '5551234',
    photo_url: 'https://images.dog.ceo/breeds/labrador/n02099712_3503.jpg',
    status: 'FOUND',
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    pet_name: 'Mruczek',
    species: 'CAT',
    breed: 'Syjamski',
    gender: 'MALE',
    description: 'Kremowy kot syjamski z niebieskimi oczami. Bardzo głośny.',
    location: 'Poznań',
    location_radius: 2,
    last_seen_date: '2025-11-12',
    email: null,
    phone: '+48 555 987 654',
    photo_url: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
    status: 'ACTIVE',
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    pet_name: 'Uszatek',
    species: 'RABBIT',
    breed: 'Królik miniaturka',
    gender: 'FEMALE',
    description: 'Mały biały królik z opadającymi uszami. Bardzo łagodny i przyjazny.',
    location: 'Łódź',
    location_radius: null,
    last_seen_date: '2025-11-16',
    email: 'joanna.mazur@example.pl',
    phone: '555-0199',
    photo_url: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400',
    status: 'ACTIVE',
  },
  {
    id: '77777777-7777-7777-7777-777777777777',
    pet_name: 'Reksio',
    species: 'DOG',
    breed: null,
    gender: 'MALE',
    description: 'Mały kundelek, płowy. Bez obroży. Lekko kuleie na lewą przednią łapę.',
    location: 'Katowice',
    location_radius: 15,
    last_seen_date: '2025-11-05',
    email: 'schronisko@example.pl',
    phone: '555-PETS',
    photo_url: 'https://images.dog.ceo/breeds/hound-basset/n02088238_9815.jpg',
    status: 'CLOSED',
  },
  {
    id: '88888888-8888-8888-8888-888888888888',
    pet_name: 'Frytka',
    species: 'OTHER',
    breed: 'Fretka',
    gender: 'MALE',
    description: 'Ciemnobrązowa fretka, bardzo zabawna. Nosi małą obrożę z dzwoneczkiem.',
    location: 'Szczecin',
    location_radius: 5,
    last_seen_date: '2025-11-14',
    email: 'wlasciciel.fretki@example.pl',
    phone: '+48-312-555-0142',
    photo_url: 'https://zooart.com.pl/blog/wp-content/uploads/2020/10/ile-zyje-fretka-4.jpeg',
    status: 'ACTIVE',
  },
];

export async function seed(knex: Knex): Promise<void> {
  await knex('announcement').del();
  await knex('announcement').insert(ANNOUNCEMENTS);
}
